# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import control_loop_pb2 as control__loop__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_loop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlLoopServiceStub(object):
    """──────────────────────────────────────────────
    Service
    ──────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/criocontrol.ControlLoopService/GetStatus',
                request_serializer=control__loop__pb2.Empty.SerializeToString,
                response_deserializer=control__loop__pb2.ControlLoopStatus.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/criocontrol.ControlLoopService/StreamStatus',
                request_serializer=control__loop__pb2.Empty.SerializeToString,
                response_deserializer=control__loop__pb2.ControlLoopStatus.FromString,
                _registered_method=True)
        self.SetAIOverride = channel.unary_unary(
                '/criocontrol.ControlLoopService/SetAIOverride',
                request_serializer=control__loop__pb2.AIOverrideRequest.SerializeToString,
                response_deserializer=control__loop__pb2.AckResponse.FromString,
                _registered_method=True)
        self.SetAOOverride = channel.unary_unary(
                '/criocontrol.ControlLoopService/SetAOOverride',
                request_serializer=control__loop__pb2.AOOverrideRequest.SerializeToString,
                response_deserializer=control__loop__pb2.AckResponse.FromString,
                _registered_method=True)
        self.SetSetpoint = channel.unary_unary(
                '/criocontrol.ControlLoopService/SetSetpoint',
                request_serializer=control__loop__pb2.SetpointRequest.SerializeToString,
                response_deserializer=control__loop__pb2.AckResponse.FromString,
                _registered_method=True)
        self.SetGain = channel.unary_unary(
                '/criocontrol.ControlLoopService/SetGain',
                request_serializer=control__loop__pb2.GainRequest.SerializeToString,
                response_deserializer=control__loop__pb2.AckResponse.FromString,
                _registered_method=True)
        self.ClearOverrides = channel.unary_unary(
                '/criocontrol.ControlLoopService/ClearOverrides',
                request_serializer=control__loop__pb2.Empty.SerializeToString,
                response_deserializer=control__loop__pb2.AckResponse.FromString,
                _registered_method=True)


class ControlLoopServiceServicer(object):
    """──────────────────────────────────────────────
    Service
    ──────────────────────────────────────────────

    """

    def GetStatus(self, request, context):
        """Returns the current snapshot of the control loop.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Streams status updates at ~10 Hz (one per control-loop tick).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAIOverride(self, request, context):
        """Enable / disable an override on the analog-input reading.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAOOverride(self, request, context):
        """Enable / disable an override on the analog-output writing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSetpoint(self, request, context):
        """Update the control-loop setpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGain(self, request, context):
        """Update the proportional gain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOverrides(self, request, context):
        """Clear all overrides in one call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlLoopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=control__loop__pb2.Empty.FromString,
                    response_serializer=control__loop__pb2.ControlLoopStatus.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=control__loop__pb2.Empty.FromString,
                    response_serializer=control__loop__pb2.ControlLoopStatus.SerializeToString,
            ),
            'SetAIOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAIOverride,
                    request_deserializer=control__loop__pb2.AIOverrideRequest.FromString,
                    response_serializer=control__loop__pb2.AckResponse.SerializeToString,
            ),
            'SetAOOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAOOverride,
                    request_deserializer=control__loop__pb2.AOOverrideRequest.FromString,
                    response_serializer=control__loop__pb2.AckResponse.SerializeToString,
            ),
            'SetSetpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSetpoint,
                    request_deserializer=control__loop__pb2.SetpointRequest.FromString,
                    response_serializer=control__loop__pb2.AckResponse.SerializeToString,
            ),
            'SetGain': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGain,
                    request_deserializer=control__loop__pb2.GainRequest.FromString,
                    response_serializer=control__loop__pb2.AckResponse.SerializeToString,
            ),
            'ClearOverrides': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOverrides,
                    request_deserializer=control__loop__pb2.Empty.FromString,
                    response_serializer=control__loop__pb2.AckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'criocontrol.ControlLoopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('criocontrol.ControlLoopService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlLoopService(object):
    """──────────────────────────────────────────────
    Service
    ──────────────────────────────────────────────

    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criocontrol.ControlLoopService/GetStatus',
            control__loop__pb2.Empty.SerializeToString,
            control__loop__pb2.ControlLoopStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/criocontrol.ControlLoopService/StreamStatus',
            control__loop__pb2.Empty.SerializeToString,
            control__loop__pb2.ControlLoopStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAIOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criocontrol.ControlLoopService/SetAIOverride',
            control__loop__pb2.AIOverrideRequest.SerializeToString,
            control__loop__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAOOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criocontrol.ControlLoopService/SetAOOverride',
            control__loop__pb2.AOOverrideRequest.SerializeToString,
            control__loop__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSetpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criocontrol.ControlLoopService/SetSetpoint',
            control__loop__pb2.SetpointRequest.SerializeToString,
            control__loop__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criocontrol.ControlLoopService/SetGain',
            control__loop__pb2.GainRequest.SerializeToString,
            control__loop__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearOverrides(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/criocontrol.ControlLoopService/ClearOverrides',
            control__loop__pb2.Empty.SerializeToString,
            control__loop__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
