# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_loop.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'control_loop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ontrol_loop.proto\x12\x0b\x63riocontrol\"\x07\n\x05\x45mpty\"\x81\x02\n\x11\x43ontrolLoopStatus\x12\x10\n\x08\x61i_value\x18\x01 \x01(\x01\x12\x10\n\x08\x61o_value\x18\x02 \x01(\x01\x12\x10\n\x08setpoint\x18\x03 \x01(\x01\x12\r\n\x05\x65rror\x18\x04 \x01(\x01\x12\x1a\n\x12\x61i_override_active\x18\x05 \x01(\x08\x12\x19\n\x11\x61i_override_value\x18\x06 \x01(\x01\x12\x1a\n\x12\x61o_override_active\x18\x07 \x01(\x08\x12\x19\n\x11\x61o_override_value\x18\x08 \x01(\x01\x12\n\n\x02kp\x18\t \x01(\x01\x12\x14\n\x0cloop_running\x18\n \x01(\x08\x12\x17\n\x0fiteration_count\x18\x0b \x01(\x04\"2\n\x11\x41IOverrideRequest\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x01\"2\n\x11\x41OOverrideRequest\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x01\"#\n\x0fSetpointRequest\x12\x10\n\x08setpoint\x18\x01 \x01(\x01\"\x19\n\x0bGainRequest\x12\n\n\x02kp\x18\x01 \x01(\x01\"/\n\x0b\x41\x63kResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf7\x03\n\x12\x43ontrolLoopService\x12?\n\tGetStatus\x12\x12.criocontrol.Empty\x1a\x1e.criocontrol.ControlLoopStatus\x12\x44\n\x0cStreamStatus\x12\x12.criocontrol.Empty\x1a\x1e.criocontrol.ControlLoopStatus0\x01\x12I\n\rSetAIOverride\x12\x1e.criocontrol.AIOverrideRequest\x1a\x18.criocontrol.AckResponse\x12I\n\rSetAOOverride\x12\x1e.criocontrol.AOOverrideRequest\x1a\x18.criocontrol.AckResponse\x12\x45\n\x0bSetSetpoint\x12\x1c.criocontrol.SetpointRequest\x1a\x18.criocontrol.AckResponse\x12=\n\x07SetGain\x12\x18.criocontrol.GainRequest\x1a\x18.criocontrol.AckResponse\x12>\n\x0e\x43learOverrides\x12\x12.criocontrol.Empty\x1a\x18.criocontrol.AckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_loop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_CONTROLLOOPSTATUS']._serialized_start=45
  _globals['_CONTROLLOOPSTATUS']._serialized_end=302
  _globals['_AIOVERRIDEREQUEST']._serialized_start=304
  _globals['_AIOVERRIDEREQUEST']._serialized_end=354
  _globals['_AOOVERRIDEREQUEST']._serialized_start=356
  _globals['_AOOVERRIDEREQUEST']._serialized_end=406
  _globals['_SETPOINTREQUEST']._serialized_start=408
  _globals['_SETPOINTREQUEST']._serialized_end=443
  _globals['_GAINREQUEST']._serialized_start=445
  _globals['_GAINREQUEST']._serialized_end=470
  _globals['_ACKRESPONSE']._serialized_start=472
  _globals['_ACKRESPONSE']._serialized_end=519
  _globals['_CONTROLLOOPSERVICE']._serialized_start=522
  _globals['_CONTROLLOOPSERVICE']._serialized_end=1025
# @@protoc_insertion_point(module_scope)
